DOMAIN = "owserver"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_POLL_INTERVAL = "poll_interval"
CONF_ENABLE_PANEL = "enable_panel"

DEFAULT_PORT = 80
DEFAULT_POLL_INTERVAL = 30
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "eds"
DEFAULT_ENABLE_PANEL = True

DETAILS_XML_PATH = "/details.xml"
MIN_POLL_INTERVAL = 10
